### ISSUE TITLE
Fatal error runing example

### ISSUE THREAD

**Issue by Andi-K** [slashmili/fighter#15]
Hello!
I use HHVM 3.11.0 and this code:

``` Hack
<?hh

require_once __DIR__ .'/vendor/autoload.php';

$app = new Fighter\Application();
$app->route('/', () ==> 'Hello World');

$app->run();
```

and get this Error:

Fatal error: Uncaught TypeError: Argument 1 passed to Fighter\Application::defaultStartHandler() must be an instance of Fighter\Net\Request, null given in /vendor/fighter/fighter/src/Fighter/Application.php:85

**Comment by slashmili** [comment]
I've merged your Pull request.

Thanks for the patches
